export const data = [
  {
    processId: 9,
    product: 'OnePlus 11',
    customer: 'Δημήτρης Σ.',
    customerId: '6677889900',
    issue: 'Battery swelling - Safety hazard',
    priority: 'Critical',
    waitingTime: '3 days',
    status: 'inProgress',
    assignedTo: 'Καραγιάννη Μ.',
    createdAt: '2025-12-02',
    expectedCost: 160,
    requiredAction: 'paymentRequired',
    notifications: [
      {
        id: 1,
        title: 'Battery swelling - Safety hazard',
        message: 'The battery is swelling and is a safety hazard.',
        createdAt: '2025-12-02',
      },
      {
        id: 2,
        title: 'Battery swelling - Safety hazard',
        message: 'The battery is swelling and is a safety hazard.',
        createdAt: '2025-12-02',
      },
      {
        id: 3,
        title: 'Battery swelling - Safety hazard',
        message: 'The battery is swelling and is a safety hazard.',
        createdAt: '2025-12-02',
      },
      {
        id: 4,
        title: 'Battery swelling - Safety hazard',
        message: 'The battery is swelling and is a safety hazard.',
        createdAt: '2025-12-02',
      },
    ],
  },
  {
    processId: 14,
    product: 'iPhone 13',
    customer: 'Ελένη Μ.',
    customerId: '5544332211',
    issue: "Water damage, won't power on",
    priority: 'High',
    waitingTime: '2 days',
    status: 'inProgress',
    assignedTo: 'Παπαδόπουλος Ν.',
    createdAt: '2025-12-03',
    expectedCost: 280,
    requiredAction: null,
    notifications: [],
  },
  {
    processId: 11,
    product: 'MacBook Air M2',
    customer: 'Κώστας Γ.',
    customerId: '9988776655',
    issue: 'Keyboard and trackpad not responding',
    priority: 'High',
    waitingTime: '1 day',
    status: 'pending',
    assignedTo: 'Νικολάου Γ.',
    createdAt: '2025-12-04',
    expectedCost: 220,
    requiredAction: 'confirmReplacement',
    notifications: [
      {
        id: 1,
        title: 'Keyboard and trackpad not responding',
        message: 'The keyboard and trackpad are not responding.',
        createdAt: '2025-12-02',
      },
    ],
  },
  {
    processId: 7,
    product: 'Samsung Galaxy Tab S8',
    customer: 'Αγγελική Π.',
    customerId: '3322114455',
    issue: 'Screen flickering, possible hardware fault',
    priority: 'Medium',
    waitingTime: '4 days',
    status: 'pending',
    assignedTo: 'Καραγιάννη Μ.',
    createdAt: '2025-12-01',
    expectedCost: 190,
    requiredAction: 'changeProcessStatus',
    notifications: [
      {
        id: 1,
        title: 'Process status changed',
        message: 'The process status has been changed.',
        createdAt: '2025-12-02',
      },
    ],
  },
  {
    processId: 18,
    product: 'Canon Pixma Printer',
    customer: 'Βασίλης Κ.',
    customerId: '1122998877',
    issue: 'Error code 5100, carriage stuck',
    priority: 'Medium',
    waitingTime: '5 hours',
    status: 'completed',
    assignedTo: 'Παπαδόπουλος Ν.',
    createdAt: '2025-12-05',
    expectedCost: 85,
    requiredAction: 'View Details',
    notifications: [
      {
        id: 1,
        title: 'Error code 5100, carriage stuck',
        message: 'The printer is stuck and is not printing.',
        createdAt: '2025-12-02',
      },
    ],
  },
  {
    processId: 22,
    product: 'Nintendo Switch',
    customer: 'Σοφία Α.',
    customerId: '7788996655',
    issue: 'Joy-Con drift, buttons sticking',
    priority: 'Low',
    waitingTime: '6 days',
    status: 'completed',
    assignedTo: 'Νικολάου Γ.',
    createdAt: '2025-11-29',
    expectedCost: 65,
    requiredAction: 'View Details',
    notifications: [
      {
        id: 1,
        title: 'Joy-Con drift, buttons sticking',
        message: 'The Joy-Con is drifting and is not sticking.',
        createdAt: '2025-12-02',
      },
    ],
  },
  {
    processId: 25,
    product: 'Asus ROG Laptop',
    customer: 'Θανάσης Λ.',
    customerId: '4455667788',
    issue: 'Blue screen errors, suspected RAM issue',
    priority: 'High',
    waitingTime: '2 days',
    status: 'inProgress',
    assignedTo: 'Παπαδόπουλος Ν.',
    createdAt: '2025-12-03',
    expectedCost: 175,
    requiredAction: 'View Details',
    notifications: [
      {
        id: 1,
        title: 'Blue screen errors, suspected RAM issue',
        message: 'The device is having blue screen errors and is suspected to have a RAM issue.',
        createdAt: '2025-12-02',
      },
    ],
  },
  {
    processId: 16,
    product: 'Apple Watch Series 8',
    customer: 'Κατερίνα Δ.',
    customerId: '2233445566',
    issue: 'Screen cracked, touch not working',
    priority: 'Critical',
    waitingTime: '3 days',
    status: 'pending',
    assignedTo: 'Καραγιάννη Μ.',
    createdAt: '2025-12-02',
    expectedCost: 210,
    requiredAction: 'View Details',
    notifications: [
      {
        id: 1,
        title: 'Screen cracked, touch not working',
        message: 'The screen is cracked and is not working.',
        createdAt: '2025-12-02',
      },
    ],
  },
  {
    processId: 30,
    product: 'Google Pixel 7',
    customer: 'Παναγιώτης Τ.',
    customerId: '8899001122',
    issue: 'Camera glass shattered, back panel cracked',
    priority: 'Medium',
    waitingTime: '1 day',
    status: 'inProgress',
    assignedTo: 'Νικολάου Γ.',
    createdAt: '2025-12-04',
    expectedCost: 140,
    requiredAction: null,
    notifications: [
      {
        id: 1,
        title: 'Camera glass shattered, back panel cracked',
        message: 'The camera glass is shattered and the back panel is cracked.',
        createdAt: '2025-12-02',
      },
    ],
  },
  {
    processId: 13,
    product: 'Epson WorkForce',
    customer: 'Χριστίνα Β.',
    customerId: '6655443322',
    issue: "Network connection issues, won't print wirelessly",
    priority: 'Low',
    waitingTime: '7 days',
    status: 'completed',
    assignedTo: 'Παπαδόπουλος Ν.',
    createdAt: '2025-11-28',
    expectedCost: 50,
    requiredAction: 'View Details',
    notifications: [
      {
        id: 1,
        title: "Network connection issues, won't print wirelessly",
        message: 'The device is not printing wirelessly.',
        createdAt: '2025-12-02',
      },
    ],
  },
  {
    processId: 19,
    product: 'Microsoft Surface Pro',
    customer: 'Αλέξανδρος Φ.',
    customerId: '9900112233',
    issue: 'Charging port loose, not charging consistently',
    priority: 'High',
    waitingTime: '1 day',
    status: 'inProgress',
    assignedTo: 'Καραγιάννη Μ.',
    createdAt: '2025-12-04',
    expectedCost: 195,
    requiredAction: 'View Details',
    notifications: [
      {
        id: 1,
        title: 'Charging port loose, not charging consistently',
        message: 'The charging port is loose and is not charging consistently.',
        createdAt: '2025-12-02',
      },
    ],
  },
  {
    processId: 27,
    product: 'Sony Xperia 5 IV',
    customer: 'Ιωάννα Ζ.',
    customerId: '1144226688',
    issue: 'Audio jack not working, speaker crackling',
    priority: 'Low',
    waitingTime: '5 days',
    status: 'completed',
    assignedTo: 'Νικολάου Γ.',
    createdAt: '2025-11-30',
    expectedCost: 80,
    requiredAction: 'View Details',
    notifications: [
      {
        id: 1,
        title: 'Audio jack not working, speaker crackling',
        message: 'The audio jack is not working and the speaker is crackling.',
        createdAt: '2025-12-02',
      },
    ],
  },
];
