export const data = [
  {
    processId: 9,
    product: 'OnePlus 11',
    customer: 'Δημήτρης Σ.',
    customerId: '6677889900',
    issue: 'Battery swelling - Safety hazard',
    priority: 'Critical',
    waitingTime: '3 days',
    status: 'In Progress',
    assignedTo: 'Καραγιάννη Μ.',
    createdAt: '2025-12-02',
    expectedCost: 160,
    actions: 'View Details',
  },
  {
    processId: 14,
    product: 'iPhone 13',
    customer: 'Ελένη Μ.',
    customerId: '5544332211',
    issue: "Water damage, won't power on",
    priority: 'High',
    waitingTime: '2 days',
    status: 'In Progress',
    assignedTo: 'Παπαδόπουλος Ν.',
    createdAt: '2025-12-03',
    expectedCost: 280,
    actions: 'View Details',
  },
  {
    processId: 11,
    product: 'MacBook Air M2',
    customer: 'Κώστας Γ.',
    customerId: '9988776655',
    issue: 'Keyboard and trackpad not responding',
    priority: 'High',
    waitingTime: '1 day',
    status: 'Pending',
    assignedTo: 'Νικολάου Γ.',
    createdAt: '2025-12-04',
    expectedCost: 220,
    actions: 'View Details',
  },
  {
    processId: 7,
    product: 'Samsung Galaxy Tab S8',
    customer: 'Αγγελική Π.',
    customerId: '3322114455',
    issue: 'Screen flickering, possible hardware fault',
    priority: 'Medium',
    waitingTime: '4 days',
    status: 'Pending',
    assignedTo: 'Καραγιάννη Μ.',
    createdAt: '2025-12-01',
    expectedCost: 190,
    actions: 'View Details',
  },
  {
    processId: 18,
    product: 'Canon Pixma Printer',
    customer: 'Βασίλης Κ.',
    customerId: '1122998877',
    issue: 'Error code 5100, carriage stuck',
    priority: 'Medium',
    waitingTime: '5 hours',
    status: 'Pending',
    assignedTo: 'Παπαδόπουλος Ν.',
    createdAt: '2025-12-05',
    expectedCost: 85,
    actions: 'View Details',
  },
  {
    processId: 22,
    product: 'Nintendo Switch',
    customer: 'Σοφία Α.',
    customerId: '7788996655',
    issue: 'Joy-Con drift, buttons sticking',
    priority: 'Low',
    waitingTime: '6 days',
    status: 'Pending',
    assignedTo: 'Νικολάου Γ.',
    createdAt: '2025-11-29',
    expectedCost: 65,
    actions: 'View Details',
  },
  {
    processId: 25,
    product: 'Asus ROG Laptop',
    customer: 'Θανάσης Λ.',
    customerId: '4455667788',
    issue: 'Blue screen errors, suspected RAM issue',
    priority: 'High',
    waitingTime: '2 days',
    status: 'In Progress',
    assignedTo: 'Παπαδόπουλος Ν.',
    createdAt: '2025-12-03',
    expectedCost: 175,
    actions: 'View Details',
  },
  {
    processId: 16,
    product: 'Apple Watch Series 8',
    customer: 'Κατερίνα Δ.',
    customerId: '2233445566',
    issue: 'Screen cracked, touch not working',
    priority: 'Critical',
    waitingTime: '3 days',
    status: 'Pending',
    assignedTo: 'Καραγιάννη Μ.',
    createdAt: '2025-12-02',
    expectedCost: 210,
    actions: 'View Details',
  },
  {
    processId: 30,
    product: 'Google Pixel 7',
    customer: 'Παναγιώτης Τ.',
    customerId: '8899001122',
    issue: 'Camera glass shattered, back panel cracked',
    priority: 'Medium',
    waitingTime: '1 day',
    status: 'In Progress',
    assignedTo: 'Νικολάου Γ.',
    createdAt: '2025-12-04',
    expectedCost: 140,
    actions: 'View Details',
  },
  {
    processId: 13,
    product: 'Epson WorkForce',
    customer: 'Χριστίνα Β.',
    customerId: '6655443322',
    issue: "Network connection issues, won't print wirelessly",
    priority: 'Low',
    waitingTime: '7 days',
    status: 'Pending',
    assignedTo: 'Παπαδόπουλος Ν.',
    createdAt: '2025-11-28',
    expectedCost: 50,
    actions: 'View Details',
  },
  {
    processId: 19,
    product: 'Microsoft Surface Pro',
    customer: 'Αλέξανδρος Φ.',
    customerId: '9900112233',
    issue: 'Charging port loose, not charging consistently',
    priority: 'High',
    waitingTime: '1 day',
    status: 'In Progress',
    assignedTo: 'Καραγιάννη Μ.',
    createdAt: '2025-12-04',
    expectedCost: 195,
    actions: 'View Details',
  },
  {
    processId: 27,
    product: 'Sony Xperia 5 IV',
    customer: 'Ιωάννα Ζ.',
    customerId: '1144226688',
    issue: 'Audio jack not working, speaker crackling',
    priority: 'Low',
    waitingTime: '5 days',
    status: 'Completed',
    assignedTo: 'Νικολάου Γ.',
    createdAt: '2025-11-30',
    expectedCost: 80,
    actions: 'View Details',
  },
];
