export const data = [
  {
    processId: 1,
    product: 'iPhone 14 Pro',
    category: 'Phones',
    description: 'Broken screen, touch not responding',
    status: 'Pending',
    createdAt: '2025-12-01',
    expectedCost: 250,
    assignedTo: 'Παπαδόπουλος Ν.',
    actions: 'View Details',
  },
  {
    processId: 2,
    product: 'MacBook Pro 16"',
    category: 'Laptops',
    description: 'Battery draining fast, overheating',
    status: 'Completed',
    createdAt: '2025-11-28',
    expectedCost: 180,
    assignedTo: 'Νικολάου Γ.',
    actions: 'View Details',
  },
  {
    processId: 3,
    product: 'Samsung S23 Ultra',
    category: 'Phones',
    description: 'Camera module not working',
    status: 'Pending',
    createdAt: '2025-11-30',
    expectedCost: 320,
    assignedTo: 'Καραγιάννη Μ.',
    actions: 'View Details',
  },
  {
    processId: 4,
    product: 'HP OfficeJet Pro',
    category: 'Printers',
    description: 'Paper jam, printing quality poor',
    status: 'In Progress',
    createdAt: '2025-12-02',
    expectedCost: 75,
    assignedTo: 'Παπαδόπουλος Ν.',
    actions: 'View Details',
  },
  {
    processId: 5,
    product: 'Dell XPS 15',
    category: 'Laptops',
    description: 'Keyboard keys stuck after coffee spill',
    status: 'Completed',
    createdAt: '2025-11-25',
    expectedCost: 140,
    assignedTo: 'Νικολάου Γ.',
    actions: 'View Details',
  },
  {
    processId: 6,
    product: 'PlayStation 5',
    category: 'Consoles',
    description: 'No display output, blue light flashing',
    status: 'Pending',
    createdAt: '2025-12-03',
    expectedCost: 150,
    assignedTo: 'Καραγιάννη Μ.',
    actions: 'View Details',
  },
  {
    processId: 7,
    product: 'iPad Air',
    category: 'Tablets',
    description: "Won't charge, port damaged",
    status: 'In Progress',
    createdAt: '2025-11-29',
    expectedCost: 95,
    assignedTo: 'Παπαδόπουλος Ν.',
    actions: 'View Details',
  },
  {
    processId: 8,
    product: 'Epson EcoTank',
    category: 'Printers',
    description: 'Ink leaking, error codes showing',
    status: 'Cancelled',
    createdAt: '2025-12-01',
    expectedCost: 110,
    assignedTo: 'Νικολάου Γ.',
    actions: 'View Details',
  },
  {
    processId: 9,
    product: 'OnePlus 11',
    category: 'Phones',
    description: 'Battery swelling, back cover lifted',
    status: 'Cancelled',
    createdAt: '2025-12-04',
    expectedCost: 160,
    assignedTo: 'Καραγιάννη Μ.',
    actions: 'View Details',
  },
  {
    processId: 10,
    product: 'Xbox Series X',
    category: 'Consoles',
    description: "Disc drive making loud noise, won't read",
    status: 'Completed',
    createdAt: '2025-11-27',
    expectedCost: 135,
    assignedTo: 'Παπαδόπουλος Ν.',
    actions: 'View Details',
  },
];
