export const data = [
  {
    processId: 1,
    customer_id: '1234567890',
    product: 'iPhone 12',
    product_category: 'phones',
    name: 'Repair',
    description: 'No power, device does not turn on.',
    status: 'Pending',
    createdAt: '2021-01-01',
    updatedAt: '2021-01-01',
    expected_cost: 100,
    assigned_tech_id: 'Papadopoulos N.',
    notification: [
      {
        notificationId: '15a',
        message: 'sjdkajshda',
      },
      {
        notificationId: '15b',
        message: 'asblablaj',
      },
    ],
  },
  {
    processId: 2,
    customer_id: '9876543210',
    product: 'Dell XPS 13',
    product_category: 'laptops',
    name: 'Repair',
    description: 'Overheating and sudden shutdowns under load.',
    status: 'In Progress',
    createdAt: '2021-01-03',
    updatedAt: '2021-01-05',
    expected_cost: 180,
    assigned_tech_id: 'Nikolaou G.',
  },
  {
    processId: 3,
    customer_id: '5556667778',
    product: 'Samsung Galaxy S21',
    product_category: 'phones',
    name: 'Screen Replacement',
    description: 'Cracked display, touch partially unresponsive.',
    status: 'Waiting Parts',
    createdAt: '2021-01-04',
    updatedAt: '2021-01-06',
    expected_cost: 220,
    assigned_tech_id: 'Papadopoulos N.',
  },
  {
    processId: 4,
    customer_id: '1122334455',
    product: 'HP LaserJet Pro',
    product_category: 'printers',
    name: 'Repair',
    description: 'Paper jams every 2–3 pages, strange noise.',
    status: 'Pending',
    createdAt: '2021-01-07',
    updatedAt: '2021-01-07',
    expected_cost: 90,
    assigned_tech_id: 'Karagianni M.',
  },
  {
    processId: 5,
    customer_id: '2233445566',
    product: 'Lenovo ThinkPad T14',
    product_category: 'laptops',
    name: 'Keyboard Replacement',
    description: 'Several keys not working after liquid spill.',
    status: 'Completed',
    createdAt: '2021-01-02',
    updatedAt: '2021-01-08',
    expected_cost: 150,
    assigned_tech_id: 'Nikolaou G.',
  },
  {
    processId: 6,
    customer_id: '3344556677',
    product: 'PlayStation 5',
    product_category: 'consoles',
    name: 'Repair',
    description: 'No video output, white light on console.',
    status: 'In Diagnostics',
    createdAt: '2021-01-09',
    updatedAt: '2021-01-10',
    expected_cost: 130,
    assigned_tech_id: 'Papadopoulos N.',
  },
];
