export const data = [
  {
    processId: 1,
    product: 'iPhone 14 Pro',
    category: 'Phones',
    description: 'Broken screen, touch not responding',
    status: 'Pending',
    createdAt: '2025-12-01',
    expectedCost: 250,
    assignedTo: 'Παπαδόπουλος Ν.',
    actions: 'View Details',
    notifications: [],
    returnStage: 'RECEIVED',
  },
  {
    processId: 2,
    product: 'Samsung Galaxy S23 Ultra',
    category: 'Phones',
    description: 'Camera focus issue, photos blurry',
    status: 'In Progress',
    createdAt: '2025-12-01',
    expectedCost: 180,
    assignedTo: 'Καραγιάννη Μ.',
    actions: 'View Details',
    notifications: [],
    returnStage: 'DIAGNOSIS',
  },
  {
    processId: 3,
    product: 'Xiaomi 13',
    category: 'Phones',
    description: 'Random reboots after update',
    status: 'Pending',
    createdAt: '2025-12-02',
    expectedCost: 90,
    assignedTo: 'Γεωργίου Α.',
    actions: 'View Details',
    notifications: [],
    returnStage: 'RECEIVED',
  },
  {
    processId: 4,
    product: 'Google Pixel 8',
    category: 'Phones',
    description: 'USB-C port loose, charging disconnects',
    status: 'In Progress',
    createdAt: '2025-12-02',
    expectedCost: 120,
    assignedTo: 'Ιωάννου Κ.',
    actions: 'View Details',
    notifications: [],
    returnStage: 'REPAIR',
  },
  {
    processId: 5,
    product: 'iPhone 13',
    category: 'Phones',
    description: 'Face ID not available',
    status: 'Completed',
    createdAt: '2025-12-02',
    expectedCost: 140,
    assignedTo: 'Παπαδόπουλος Ν.',
    actions: 'View Details',
    notifications: [],
    returnStage: 'READY_FOR_RETURN',
  },
  {
    processId: 6,
    product: 'Huawei P50 Pro',
    category: 'Phones',
    description: 'No network signal, SIM not detected',
    status: 'Pending',
    createdAt: '2025-12-03',
    expectedCost: 110,
    assignedTo: 'Κωνσταντίνου Σ.',
    actions: 'View Details',
    notifications: [],
    returnStage: 'RECEIVED',
  },
  {
    processId: 7,
    product: 'Nothing Phone (2)',
    category: 'Phones',
    description: 'Speakers crackling at high volume',
    status: 'In Progress',
    createdAt: '2025-12-03',
    expectedCost: 75,
    assignedTo: 'Βασιλείου Π.',
    actions: 'View Details',
    notifications: [],
    returnStage: 'DIAGNOSIS',
  },
  {
    processId: 8,
    product: 'Motorola Edge 40',
    category: 'Phones',
    description: 'Overheating during calls',
    status: 'Pending',
    createdAt: '2025-12-03',
    expectedCost: 95,
    assignedTo: 'Δημητρίου Ε.',
    actions: 'View Details',
    notifications: [],
    returnStage: 'RECEIVED',
  },
  {
    processId: 9,
    product: 'OnePlus 11',
    category: 'Phones',
    description: 'Battery swelling, back cover lifted',
    status: 'Cancelled',
    createdAt: '2025-12-04',
    expectedCost: 160,
    assignedTo: 'Καραγιάννη Μ.',
    actions: 'View Details',
    notifications: [],
    returnStage: 'DIAGNOSIS',
  },
  {
    processId: 10,
    product: 'Sony Xperia 1 V',
    category: 'Phones',
    description: 'Mic not working on video recording',
    status: 'Pending',
    createdAt: '2025-12-04',
    expectedCost: 85,
    assignedTo: 'Γεωργίου Α.',
    actions: 'View Details',
    notifications: [],
    returnStage: 'RECEIVED',
  },
  {
    processId: 11,
    product: 'iPad Pro 11',
    category: 'Tablets',
    description: 'Touch input intermittent near edges',
    status: 'In Progress',
    createdAt: '2025-12-04',
    expectedCost: 220,
    assignedTo: 'Ιωάννου Κ.',
    actions: 'View Details',
    notifications: [],
    returnStage: 'DIAGNOSIS',
  },
  {
    processId: 12,
    product: 'Samsung Galaxy Tab S9',
    category: 'Tablets',
    description: 'S Pen not pairing, no hover',
    status: 'Pending',
    createdAt: '2025-12-05',
    expectedCost: 60,
    assignedTo: 'Κωνσταντίνου Σ.',
    actions: 'View Details',
    notifications: [],
    returnStage: 'RECEIVED',
  },
  {
    processId: 13,
    product: 'Lenovo Tab P12',
    category: 'Tablets',
    description: 'Screen flickers on low brightness',
    status: 'Completed',
    createdAt: '2025-12-05',
    expectedCost: 130,
    assignedTo: 'Βασιλείου Π.',
    actions: 'View Details',
    notifications: [],
    returnStage: 'READY_FOR_RETURN',
  },
  {
    processId: 14,
    product: 'MacBook Air M2',
    category: 'Laptops',
    description: 'Keyboard keys sticky, double typing',
    status: 'In Progress',
    createdAt: '2025-12-05',
    expectedCost: 190,
    assignedTo: 'Δημητρίου Ε.',
    actions: 'View Details',
    notifications: [],
    returnStage: 'REPAIR',
  },
  {
    processId: 15,
    product: 'Dell XPS 13',
    category: 'Laptops',
    description: 'Battery drains fast, won’t hold charge',
    status: 'Pending',
    createdAt: '2025-12-06',
    expectedCost: 210,
    assignedTo: 'Παπαδόπουλος Ν.',
    actions: 'View Details',
    notifications: [],
    returnStage: 'RECEIVED',
  },
  {
    processId: 16,
    product: 'HP Spectre x360',
    category: 'Laptops',
    description: 'Hinge loose, screen wobbling',
    status: 'In Progress',
    createdAt: '2025-12-06',
    expectedCost: 170,
    assignedTo: 'Καραγιάννη Μ.',
    actions: 'View Details',
    notifications: [],
    returnStage: 'DIAGNOSIS',
  },
  {
    processId: 17,
    product: 'ASUS ROG Zephyrus G14',
    category: 'Laptops',
    description: 'Fan noise loud, overheating while gaming',
    status: 'Pending',
    createdAt: '2025-12-06',
    expectedCost: 150,
    assignedTo: 'Γεωργίου Α.',
    actions: 'View Details',
    notifications: [],
    returnStage: 'RECEIVED',
  },
  {
    processId: 18,
    product: 'Acer Swift 3',
    category: 'Laptops',
    description: 'Wi‑Fi drops frequently',
    status: 'Completed',
    createdAt: '2025-12-07',
    expectedCost: 80,
    assignedTo: 'Ιωάννου Κ.',
    actions: 'View Details',
    notifications: [],
    returnStage: 'READY_FOR_RETURN',
  },
  {
    processId: 19,
    product: 'PlayStation 5',
    category: 'Consoles',
    description: 'Overheats and shuts down',
    status: 'In Progress',
    createdAt: '2025-12-07',
    expectedCost: 140,
    assignedTo: 'Κωνσταντίνου Σ.',
    actions: 'View Details',
    notifications: [],
    returnStage: 'REPAIR',
  },
  {
    processId: 20,
    product: 'Xbox Series X',
    category: 'Consoles',
    description: 'Disc drive not accepting discs',
    status: 'Pending',
    createdAt: '2025-12-07',
    expectedCost: 125,
    assignedTo: 'Βασιλείου Π.',
    actions: 'View Details',
    notifications: [],
    returnStage: 'RECEIVED',
  },
  {
    processId: 21,
    product: 'Nintendo Switch OLED',
    category: 'Consoles',
    description: 'Joy-Con drift on left controller',
    status: 'Completed',
    createdAt: '2025-12-08',
    expectedCost: 45,
    assignedTo: 'Δημητρίου Ε.',
    actions: 'View Details',
    notifications: [],
    returnStage: 'READY_FOR_RETURN',
  },
  {
    processId: 22,
    product: 'AirPods Pro (2nd Gen)',
    category: 'Accessories',
    description: 'Left earbud low volume',
    status: 'Pending',
    createdAt: '2025-12-08',
    expectedCost: 70,
    assignedTo: 'Παπαδόπουλος Ν.',
    actions: 'View Details',
    notifications: [],
    returnStage: 'RECEIVED',
  },
  {
    processId: 23,
    product: 'Apple Watch Series 9',
    category: 'Wearables',
    description: 'Won’t power on after swimming',
    status: 'Cancelled',
    createdAt: '2025-12-08',
    expectedCost: 200,
    assignedTo: 'Καραγιάννη Μ.',
    actions: 'View Details',
    notifications: [],
    returnStage: 'DIAGNOSIS',
  },
  {
    processId: 24,
    product: 'Samsung Galaxy Watch 6',
    category: 'Wearables',
    description: 'Heart rate sensor inconsistent readings',
    status: 'In Progress',
    createdAt: '2025-12-09',
    expectedCost: 65,
    assignedTo: 'Γεωργίου Α.',
    actions: 'View Details',
    notifications: [],
    returnStage: 'DIAGNOSIS',
  },
  {
    processId: 25,
    product: 'Kindle Paperwhite',
    category: 'E-Readers',
    description: 'Ghosting on screen, slow refresh',
    status: 'Pending',
    createdAt: '2025-12-09',
    expectedCost: 55,
    assignedTo: 'Ιωάννου Κ.',
    actions: 'View Details',
    notifications: [],
    returnStage: 'RECEIVED',
  },
  {
    processId: 26,
    product: 'Bose QC45',
    category: 'Audio',
    description: 'ANC not working, constant hiss',
    status: 'In Progress',
    createdAt: '2025-12-09',
    expectedCost: 90,
    assignedTo: 'Κωνσταντίνου Σ.',
    actions: 'View Details',
    notifications: [],
    returnStage: 'REPAIR',
  },
  {
    processId: 27,
    product: 'Logitech MX Master 3S',
    category: 'Peripherals',
    description: 'Scroll wheel jittering',
    status: 'Completed',
    createdAt: '2025-12-10',
    expectedCost: 35,
    assignedTo: 'Βασιλείου Π.',
    actions: 'View Details',
    notifications: [],
    returnStage: 'READY_FOR_RETURN',
  },
  {
    processId: 28,
    product: 'Canon EOS R10',
    category: 'Cameras',
    description: 'Sensor dust spots visible in photos',
    status: 'Pending',
    createdAt: '2025-12-10',
    expectedCost: 100,
    assignedTo: 'Δημητρίου Ε.',
    actions: 'View Details',
    notifications: [],
    returnStage: 'RECEIVED',
  },
  {
    processId: 29,
    product: 'DJI Mini 3',
    category: 'Drones',
    description: 'Gimbal stuck, error on startup',
    status: 'In Progress',
    createdAt: '2025-12-10',
    expectedCost: 160,
    assignedTo: 'Παπαδόπουλος Ν.',
    actions: 'View Details',
    notifications: [],
    returnStage: 'DIAGNOSIS',
  },
  {
    processId: 30,
    product: 'GoPro Hero 12',
    category: 'Cameras',
    description: 'SD card error, recording stops',
    status: 'Pending',
    createdAt: '2025-12-11',
    expectedCost: 75,
    assignedTo: 'Καραγιάννη Μ.',
    actions: 'View Details',
    notifications: [],
    returnStage: 'RECEIVED',
  },
];
